[changelog]
header = """
# Changelog

All notable changes to Jamesium Industries will be documented in this file.

"""
body = """
{% if version %}
## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits %}
- {{ commit.message | upper_first }}
{% endfor %}

{% endfor %}
"""
trim = true

[git]
processing_order = [
    "commit_preprocessors",
    "split_commits",
    "conventional_commits",
    "commit_parsers",
    "link_parsers",
]

conventional_commits = true
filter_unconventional = true

commit_preprocessors = [
    { pattern = "^Initial commit$", replace = "feat: initial commit" },
    { pattern = "^Added inital files via upload$", replace = "feat: add initial files via upload" },
    { pattern = "^Migrate tutorial mod from Forge 1\\.11\\.2 to Neoforge 1\\.21\\.11$", replace = "chore: migrate tutorial mod from Forge 1.11.2 to NeoForge 1.21.11" },
    { pattern = "^Basic Block and Item with assets$", replace = "feat: add basic block and item assets" },
    { pattern = "^Commence rewiring into logical modules$", replace = "refactor: commence rewiring into logical modules" },
    { pattern = "^Fix Gradlew Permissions$", replace = "fix: gradlew permissions" },
    { pattern = "^Force add missing gradle-wrapper\\.jar$", replace = "fix: add missing gradle-wrapper.jar" },
]

commit_parsers = [
    { message = "(?i)^feat", group = "Added" },
    { message = "(?i)^fix", group = "Fixed" },
    { message = "(?i)^perf", group = "Performance" },
    { message = "(?i)^chore", group = "Changed" },

    { message = "(?i)^refactor", skip = true },
    { message = "(?i)^doc", skip = true },
    { message = "(?i)^style", skip = true },
    { message = "(?i)^test", skip = true },
    { message = "(?i)^ci", skip = true },
    { message = "(?i)^build", skip = true },
]